"""Add files table

Revision ID: b8d7da233dd7
Revises: f5c105806b68
Create Date: 2025-09-25 01:24:51.178858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d7da233dd7'
down_revision: Union[str, None] = 'f5c105806b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_created_at', table_name='files')
    op.drop_index('idx_files_filename', table_name='files')
    op.drop_index('idx_files_user_id', table_name='files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_files_user_id', 'files', ['user_id'], unique=False)
    op.create_index('idx_files_filename', 'files', ['filename'], unique=False)
    op.create_index('idx_files_created_at', 'files', ['created_at'], unique=False)
    # ### end Alembic commands ###
